name: CI - Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: subosito/flutter-action@v2
        with:
          fluetter-version: "3.19.4"
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }} "
          echo "Environment variable TEST_VAR: ${{ vars.API_URL }}"
          echo "TESTE variable TESTE: ${{ vars.TESTE }}"
      
      - uses: actions/upload-artifact@v4
        with:
          name: android-outputs
          path: build/app/outputs/
     
