name: CI - Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: greet
        run: | 
          echo "environment is ${{ github.event.inputs.environment }} / ${{ inputs.environment }}"
          echo "API URL ${{ env.vars.API_URL }}"
          echo "API URL ${{ github.event.vars.API_URL }}"
          echo "API URL ${{ env.API_URL }}"
