name: CI - Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }} "
          echo "Environment variable TEST_VAR: ${{ vars.API_URL }}"
          echo "TESTE variable TESTE: ${{ vars.TESTE }}"


      - name: MKDIR
        run: mkdir ${vars}.API_URL

      - name: MKDIR
        run: ls
     
