name: CI - Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        
jobs:
  build_android:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: subosito/flutter-action@v2
        with:
          fluetter-version: "3.19.4"
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }} "
          echo "Environment variable TEST_VAR: ${{ vars.API_URL }}"
          echo "TESTE variable TESTE: ${{ vars.TESTE }}"
      
      - uses: actions/upload-artifact@v4
        with:
          name: android-outputs
          path: build/app/outputs/
          
  publish_artifact:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_android]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: android-outputs
      - name: Upload APK
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: testers
          releaseNotesFile: RELEASENOTES.md
          file: bundle/release/app-release.aab
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash
      - name: Deploy symbols to Firebase Crashlytics
        run: |
          firebase --token="${{ secrets.FIREBASE_TOKEN }}" crashlytics:symbols:upload --app="${{ secrets.FIREBASE_APP_ID }}" ./bundle/release/symbols
     
