name: CI - Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
      - uses: actions/checkout@v2
      - name: greet
        run: | 
          echo "environment is ${{ inputs.environment }} "
          echo "Environment variable TEST_VAR: ${{ vars.API_URL }}"
          echo "TESTE variable TESTE: ${{ vars.TESTE }}"
      - name: Build
        run: | 
           MY_COMMAND=("flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64 --obfuscate --split-debug-info=build/app/outputs/bundle/ --dart-define-from-file=") 
           MY_ARGUMENTS=(${{ vars.TESTE }})
           eval "${MY_COMMAND[@]}" "${MY_ARGUMENTS[@]}"
  
      - name: MKDIR
        run: |
         MY_COMMAND=("flutter build appbundle --release --target-platform android-arm,android-arm64,android-x64 --obfuscate --split-debug-info=build/app/outputs/bundle/ --dart-define-from-file=") 
         MY_ARGUMENTS=(${{ vars.ENV }})
         eval "${MY_COMMAND[@]}" "${MY_ARGUMENTS[@]}"

      - name: MKDIR
        run: ls
     
